name: matrix
on: push

jobs:
  node-version:
    strategy:
      matrix:
        os: [macos-latest, ubuntu-latest, windows-latest]
        node-version: [6,8,10]
        include:
          - os: ubuntu-latest
            node-version: 4
            is_ubuntu_8: "true"
        exclude:
          - os: ubuntu-latest
            node-version: 6
          - os: macos-latest
            node-version: 8
    #runs-on: ubuntu-latest
    runs-on: ${{ matrix.os}}
    env:
      IS_UBUNTU_8: ${{ matrix.is_ubuntu_8}}
    steps:
      - name: Log Node Version
        run: node -v
      - uses: actions/setup-node@v1
        with:
          node-version: ${{matrix.node-version}}
      - name: Log node Version
        run: |
          node -v
          echo $IS_UBUNTU_8